version: "3.9"

services:
  api:
    container_name: cg3_web_api
    build: 
      context: server
      dockerfile: dev.Dockerfile
    env_file: .env
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./server:/cg3-web-server
    environment:
      CHOKIDAR_USE_POLLING: false
    networks:
      - cg3-network
  
  astro:
    container_name: cg3_site
    build: 
      context: site
      dockerfile: dev.Dockerfile
    env_file: .env
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./site/public:/cg3-site/public
      - ./site/src:/cg3-site/src
      - ./site/tsconfig.json:/cg3-site/tsconfig.json
      - ./site/astro.config.mjs:/cg3-site/astro.config.mjs
    environment:
      CHOKIDAR_USE_POLLING: false
      SERVER_URL: http://cg3_web_api:9090
      PORT: 3000
    networks:
      - cg3-network
    depends_on:
      - api

networks:
  cg3-network: