version: "3.9"

services:
  api:
    build: 
      context: ./server
      dockerfile: dev.Dockerfile
    env_file: .env
    container_name: cg3_web_api
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./server:/app
  
  astro:
    build: 
      context: ./site
      dockerfile: /dev.Dockerfile
    env_file: .env
    container_name: cg3_site
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./astro/src:/app/src