version: '3.9'

services:
  api:
    container_name: cg3_grpc_api
    build: 
      context: server
      dockerfile: dev.Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./server:/cg3-web-server
      - ./server/config.toml:/cg3-web-server/config.toml
    environment:
      CHOKIDAR_USE_POLLING: false
    networks:
      - cg3-network
  
  next:
    container_name: cg3_next
    build: 
      context: site
      dockerfile: dev.Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./next/public:/next/public
      - ./next/src:/next/src
      - ./next/src/proto:/next/src/proto
      - ./next/tsconfig.json:/next/tsconfig.json
      - ./next/next.config.js:/next/next.config.js
      - ./next/postcss.config.js:/next/postcss.config.js
      - ./next/tailwind.config.js:/next/tailwind.config.js
    environment:
      CHOKIDAR_USE_POLLING: false
      SERVER_URL: cg3_grpc_api:8080
    networks:
      - cg3-network
    depends_on:
      - api

networks:
  cg3-network: