version: "3.9"

services:
  api:
    container_name: cg3_web_api
    build: 
      context: ./server
      dockerfile: dev.Dockerfile
    env_file: .env
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./server:/app
    environment:
      CHOKIDAR_USE_POLLING: "true"
  
  astro:
    container_name: cg3_site
    build: 
      context: ./site
      dockerfile: dev.Dockerfile
    env_file: .env
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./site:/app
      - ./site/src:/app/src
    environment:
      CHOKIDAR_USE_POLLING: "true"