package models

type Character struct {
	Id                            int    `db:"id"`
	Account                       int    `db:"accountid"`
	World                         bool   `db:"world"`
	Name                          string `db:"name"`
	Level                         int    `db:"level"`
	Exp                           int    `db:"exp"`
	Str                           int    `db:"str"`
	Dex                           int    `db:"dex"`
	Int                           int    `db:"int"`
	Luk                           int    `db:"luk"`
	HP                            int    `db:"hp"`
	MP                            int    `db:"mp"`
	MaxHP                         int    `db:"maxhp"`
	MaxMP                         int    `db:"maxmp"`
	Meso                          int    `db:"meso"`
	Job                           int    `db:"job"`
	JobName                       string
	SkinColor                     int  `db:"skincolor"`
	Gender                        bool `db:"gender"`
	Fame                          int  `db:"fame"`
	Face                          int  `db:"face"`
	Hair                          int  `db:"hair"`
	AP                            int  `db:"ap"`
	SP                            int  `db:"sp"`
	Map                           int  `db:"map"`
	StreetName                    string
	MapName                       string
	ExpRequired                   int
	SpawnPoint                    int    `db:"spawnpoint"`
	Party                         int    `db:"party"`
	BuddyCapacity                 int    `db:"buddyCapacity"`
	CreateDate                    string `db:"createdate"`
	Rank                          int    `db:"rank"`
	RankMove                      int    `db:"rankMove"`
	JobRank                       int    `db:"jobRank"`
	JobRankMove                   int    `db:"jobRankMove"`
	GuildID                       int    `db:"guildid"`
	GuildRank                     int    `db:"guildrank"`
	AllianceRank                  int    `db:"allianceRank"`
	MessengerID                   int    `db:"messengerid"`
	MessengerPosition             int    `db:"messengerposition"`
	Clan                          int    `db:"clan"`
	MountLevel                    int    `db:"mountlevel"`
	MountExp                      int    `db:"mountexp"`
	MountTiredness                int    `db:"mounttiredness"`
	Married                       bool   `db:"married"`
	PartnerId                     int    `db:"partnerid"`
	CanTalk                       bool   `db:"cantalk"`
	ZakumLvl                      bool   `db:"zakumlvl"`
	MarriageQuest                 int    `db:"marriagequest"`
	MerchantMesos                 int    `db:"MerchantMesos"`
	HasMerchant                   bool   `db:"HasMerchant"`
	GMText                        bool   `db:"gmtext"`
	EquipSlots                    int    `db:"equipslots"`
	UseSlots                      int    `db:"useslots"`
	SetupSlots                    int    `db:"setupslots"`
	EtcSlots                      int    `db:"etcslots"`
	Mute                          bool   `db:"mute"`
	MuteSmega                     bool   `db:"mutesmega"`
	GachaEXP                      int    `db:"gachaexp"`
	HPQCake                       int    `db:"hpqcake"`
	AriantWarps                   bool   `db:"ariantwarps"`
	LPQ                           int    `db:"lpq"`
	PPQ                           int    `db:"ppq"`
	KPQ                           int    `db:"kpq"`
	BGlasses                      int    `db:"bglasses"`
	SShoes                        int    `db:"sshoes"`
	FamePolicy                    bool   `db:"fame_policy"`
	EngagementId                  int    `db:"engagement_id"`
	BookCover                     int    `db:"bookcover"`
	LastCardPickup                int    `db:"last_card_pickup"`
	Islander                      bool   `db:"islander"`
	MarriageId                    int    `db:"marriageId"`
	LastLoginInMilliseconds       int    `db:"LastLoginInMilliseconds"`
	ImitateId                     int    `db:"imitateId"`
	LoggedIn                      int    `db:"loggedIn"`
	TotalPlayTime                 int    `db:"totalPlayTime"`
	SiteOverallRank               int    `db:"siteOverallRank"`
	SiteJobRank                   int    `db:"siteJobRank"`
	SiteOddJobRank                int    `db:"siteOddJobRank"`
	ActivePetSlot                 int    `db:"activePetSlot"`
	PingedLastLoginInMilliseconds int    `db:"PingedLastLoginInMilliseconds"`
	QuestsCompleted               int    `db:"questsCompleted"`
	HideFromRankings              int    `db:"hideFromRankings"`
	IsOn1xEXP                     int    `db:"isOn1xEXP"`
}
